#!/usr/bin/env python
"""
Simple script to create a test JSON file for GitHub Actions
"""

import json
from datetime import datetime

def create_test_json():
    """Create a test daily_summary.json file"""
    
    test_summary = {
        "date": datetime.now().strftime('%Y-%m-%d'),
        "generated_at": datetime.now().isoformat(),
        "summary": "# Financial Services News Summary - " + datetime.now().strftime('%B %d, %Y') + "\n\n## Test Summary\n\nThis is a test summary generated by GitHub Actions.\n\n### Status\n- GitHub Actions: ✅ Working\n- API Key: ✅ Configured\n- Python Environment: ✅ Ready\n\n---\n*Generated by GitHub Actions workflow*",
        "companies_included": ["Test Company 1", "Test Company 2", "Test Company 3"],
        "total_articles": 0,
        "time_period": "test data",
        "status": "test_success"
    }
    
    with open('daily_summary.json', 'w') as f:
        json.dump(test_summary, f, indent=2)
    
    print("✅ Test summary created successfully!")
    print(f"✅ Date: {test_summary['date']}")
    print(f"✅ Status: {test_summary['status']}")
    print(f"✅ Companies: {len(test_summary['companies_included'])}")
    
    return True

if __name__ == "__main__":
    create_test_json()