name: Daily News Collection and Summary Generation

on:
  schedule:
    # Run at 8 AM UTC (midnight PST) every day
    - cron: '0 8 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  collect-and-summarize:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas duckduckgo_search anthropic python-dotenv
        
    - name: Collect daily news
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: |
        echo "Starting news collection..."
        python collect_all_news.py --daily || echo "News collection failed, using existing data"
        
    - name: Generate daily summary JSON
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: |
        echo "Generating summary from available data..."
        # First try with latest data, fall back to test JSON if needed
        python generate_daily_summary.py || python create_test_json.py
        
    - name: Upload JSON to S3 (Optional)
      if: env.AWS_ACCESS_KEY_ID != ''
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
      run: |
        # Install AWS CLI
        pip install awscli
        # Upload to S3 bucket (replace with your bucket name)
        aws s3 cp daily_summary.json s3://z-news-data/daily_summary.json --acl public-read
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add daily_summary.json
        git add data/
        # Only commit if there are changes
        git diff --staged --quiet || (git commit -m "Daily news update: $(date +'%Y-%m-%d')" && git push)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}