name: Test Summary Generation

on:
  workflow_dispatch: # Allow manual triggering only

jobs:
  test-summary:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas anthropic python-dotenv
        
    - name: List available files
      run: |
        echo "Available files:"
        ls -la
        echo "Data directory:"
        ls -la data/ || echo "No data directory"
        echo "Sample data:"
        ls -la sample_data.csv || echo "No sample data"
        
    - name: Test summary generation with sample data
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: |
        echo "Testing summary generation..."
        if [ -f "sample_data.csv" ]; then
          echo "Using sample_data.csv"
          python generate_daily_summary.py --file sample_data.csv
        else
          echo "No sample data found, creating minimal JSON..."
          python -c "
import json
from datetime import datetime
print('Creating test summary...')
test_summary = {
    'date': datetime.now().strftime('%Y-%m-%d'),
    'generated_at': datetime.now().isoformat(),
    'summary': '# Financial Services News Summary - ' + datetime.now().strftime('%B %d, %Y') + '\n\n## Test Summary\n\nThis is a test summary generated by GitHub Actions.\n\n### Status\n- GitHub Actions: ✅ Working\n- API Key: ✅ Configured\n- Python Environment: ✅ Ready\n\n---\n*Generated by GitHub Actions workflow*',
    'companies_included': ['Test Company 1', 'Test Company 2'],
    'total_articles': 0,
    'time_period': 'test data',
    'status': 'test_success'
}
with open('daily_summary.json', 'w') as f:
    json.dump(test_summary, f, indent=2)
print('Test summary created successfully!')
"
        fi
        
    - name: Verify JSON was created
      run: |
        if [ -f "daily_summary.json" ]; then
          echo "✅ daily_summary.json created successfully"
          echo "File size: $(wc -c < daily_summary.json) bytes"
          echo "First few lines:"
          head -10 daily_summary.json
        else
          echo "❌ daily_summary.json was not created"
          exit 1
        fi
        
    - name: Test API key (without exposing it)
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: |
        if [ -z "$ANTHROPIC_API_KEY" ]; then
          echo "❌ ANTHROPIC_API_KEY is not set"
          exit 1
        else
          echo "✅ ANTHROPIC_API_KEY is configured"
          echo "Key length: ${#ANTHROPIC_API_KEY} characters"
        fi