name: Test Summary Generation

on:
  workflow_dispatch: # Allow manual triggering only

jobs:
  test-summary:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas anthropic python-dotenv
        
    - name: List available files
      run: |
        echo "Available files:"
        ls -la
        echo "Data directory:"
        ls -la data/ || echo "No data directory"
        echo "Sample data:"
        ls -la sample_data.csv || echo "No sample data"
        
    - name: Create test JSON
      run: |
        echo "Creating test JSON file..."
        python create_test_json.py
        
    - name: Verify JSON was created
      run: |
        if [ -f "daily_summary.json" ]; then
          echo "✅ daily_summary.json created successfully"
          echo "File size: $(wc -c < daily_summary.json) bytes"
          echo "First few lines:"
          head -10 daily_summary.json
        else
          echo "❌ daily_summary.json was not created"
          exit 1
        fi
        
    - name: Test API key (without exposing it)
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: |
        if [ -z "$ANTHROPIC_API_KEY" ]; then
          echo "❌ ANTHROPIC_API_KEY is not set"
          exit 1
        else
          echo "✅ ANTHROPIC_API_KEY is configured"
          echo "Key length: ${#ANTHROPIC_API_KEY} characters"
        fi